const schoolData = [
  {
    id: "1",
    title: "University of The Philippines College Admission Test",
    testName: "UPCAT",
    schoolName: "",
    examDescription:
      "The UPCAT is a 4-hour examination composed of sub-tests in English, Science, Mathematics, Filipino and Abstract Reasoning. After taking the exam, your UPCAT score will be compared to a standardized PLMAT score. If your score satisfies the suggested cut-off score, you are qualified for enrollment!",
    requirementText: "",
    admissionLinks: "",
    tipsAndTricks: "",
    image: require("../assets/images/UP.png"),
    path: "schoolDetail",
    mainColor: "#751518",
    accentColor: "#0A4424",
    textColorMain: "#FFFFFF",
    textColorSecondary: "#FFFFFF",
    subjects: ["English", "Filipino", "Science", "Mathematics", "Logic"],
  },
  {
    id: "2",
    title: "UST",
    testName: "",
    examDescriptionTitle: "",
    examDescription:
      "The USTET is a 4-hour examination composed of sub-tests in English, Science, Mathematics, Filipino and Abstract Reasoning. After taking the exam, your UPCAT score will be compared to a standardized PLMAT score. If your score satisfies the suggested cut-off score, you are qualified for enrollment!",
    schoolName: "",
    requirementText: "",
    admissionLinks: "",
    tipsAndTricks: "",
    image: require("../assets/images/UST.png"),
    path: "schoolDetail",
    mainColor: "#FEC00F",
    accentColor: "#00A2E8",
    textColorMain: "#3C3C3C",
    textColorSecondary: "#FFFFFF",
  },
  {
    id: "3",
    title: "DLSU",
    testName: "",
    examDescriptionTitle: "",
    examDescription: "",
    schoolName: "",
    requirementText: "",
    admissionLinks: "",
    tipsAndTricks: "",
    image: require("../assets/images/DLSU.png"),
    path: "schoolDetail",
    mainColor: "#FFFFFF",
    accentColor: "#006937",
    textColorMain: "#3C3C3C",
    textColorSecondary: "#FFFFFF",
  },
  {
    id: "4",
    title: "FEU",
    testName: "",
    examDescriptionTitle: "",
    examDescription: "",
    schoolName: "",
    requirementText: "",
    admissionLinks: "",
    tipsAndTricks: "",
    image: require("../assets/images/FEU.png"),
    path: "schoolDetail",
    mainColor: "#018348",
    accentColor: "#febf3b",
    textColorMain: "#FFFFFF",
    textColorSecondary: "#FFFFFF",
  },
  {
    id: "5",
    title: "EARIST",
    testName: "",
    examDescriptionTitle: "",
    examDescription: "",
    schoolName: "",
    requirementText: "",
    admissionLinks: "",
    tipsAndTricks: "",
    image: require("../assets/images/EARIST.png"),
    path: "schoolDetail",
    mainColor: "#ffffff",
    accentColor: "#fe0000",
    textColorMain: "#FFFFFF",
    textColorSecondary: "#FFFFFF",
  },
  {
    id: "6",
    title: "LYCEUM",
    testName: "",
    examDescriptionTitle: "",
    examDescription: "",
    schoolName: "",
    requirementText: "",
    admissionLinks: "",
    tipsAndTricks: "",
    image: require("../assets/images/LYCEUM.png"),
    path: "schoolDetail",
    mainColor: "#a2252f",
    accentColor: "#a18300",
    textColorMain: "#FFFFFF",
    textColorSecondary: "#FFFFFF",
  },
  {
    id: "7",
    title: "MAPUA",
    testName: "",
    examDescriptionTitle: "",
    examDescription: "",
    schoolName: "",
    requirementText: "",
    admissionLinks: "",
    tipsAndTricks: "",
    image: require("../assets/images/MAPUA.png"),
    path: "schoolDetail",
    mainColor: "#FFFFFF",
    accentColor: "#751518",
    textColorMain: "#FFFFFF",
    textColorSecondary: "#FFFFFF",
  },
  {
    id: "8",
    title: "NPA",
    testName: "",
    examDescriptionTitle: "",
    examDescription: "",
    schoolName: "",
    requirementText: "",
    admissionLinks: "",
    tipsAndTricks: "",
    image: require("../assets/images/NPA.png"),
    path: "schoolDetail",
    mainColor: "#751518",
    accentColor: "#751518",
    textColorMain: "#FFFFFF",
    textColorSecondary: "#FFFFFF",
  },
  {
    id: "9",
    title: "PMA",
    testName: "",
    examDescriptionTitle: "",
    examDescription: "",
    schoolName: "",
    requirementText: "",
    admissionLinks: "",
    tipsAndTricks: "",
    image: require("../assets/images/PMA.png"),
    path: "schoolDetail",
    mainColor: "#751518",
    accentColor: "#751518",
    textColorMain: "#FFFFFF",
    textColorSecondary: "#FFFFFF",
  },
  {
    id: "10",
    title: "PNU",
    testName: "",
    examDescriptionTitle: "",
    examDescription: "",
    schoolName: "",
    requirementText: "",
    admissionLinks: "",
    tipsAndTricks: "",
    image: require("../assets/images/PNU.png"),
    path: "schoolDetail",
    mainColor: "#751518",
    accentColor: "#751518",
    textColorMain: "#FFFFFF",
    textColorSecondary: "#FFFFFF",
  },
  {
    id: "11",
    title: "SU",
    testName: "",
    examDescriptionTitle: "",
    examDescription: "",
    schoolName: "",
    requirementText: "",
    admissionLinks: "",
    tipsAndTricks: "",
    image: require("../assets/images/SU.png"),
    path: "schoolDetail",
    mainColor: "#751518",
    accentColor: "#751518",
    textColorMain: "#FFFFFF",
    textColorSecondary: "#FFFFFF",
  },
  {
    id: "12",
    title: "TUP",
    testName: "",
    examDescriptionTitle: "",
    examDescription: "",
    schoolName: "",
    requirementText: "",
    admissionLinks: "",
    tipsAndTricks: "",
    image: require("../assets/images/TUP.png"),
    path: "schoolDetail",
    mainColor: "#751518",
    accentColor: "#751518",
    textColorMain: "#FFFFFF",
    textColorSecondary: "#FFFFFF",
  },
  {
    id: "13",
    title: "UE",
    testName: "",
    examDescriptionTitle: "",
    examDescription: "",
    schoolName: "",
    requirementText: "",
    admissionLinks: "",
    tipsAndTricks: "",
    image: require("../assets/images/UE.png"),
    path: "schoolDetail",
    mainColor: "#751518",
    accentColor: "#751518",
    textColorMain: "#FFFFFF",
    textColorSecondary: "#FFFFFF",
  },
];

export default schoolData;
